### ISSUE TITLE
Feature Request: Minimize to tray, and disengage from Discord when no song is playing

### ISSUE THREAD

**Issue by yashendra2797** [nint8835/iTunesRichPresence#1]
Dunno if this is the right place to post this, but I had 2 requests for this dope app.

1. It would be amazing if the app could minimize to the system tray rather than taking up space in the task bar.

2. It would also be awesome if the app could clear itself from Discord when no track is playing in iTunes. I don't mean detecting pauses cause thats a bit more tricky due to iTunes' shite API (or the lack of one), but if it would just not show in my Discord when no music is playing.

Cheers!

**Comment by nint8835** [comment]
Sorry, I only just noticed that you submitted this issue.
Unfortunately, it is not really possible for me to implement either of your suggestions.

For suggestion number one, Discord Rich Presence requires the application to have a window for it to detect. Minimizing the app to the system tray would get rid of this window, causing the app to stop being detected.

For suggestion number two, as long as the window is opened, Discord will display that app as being running. In order for me to clear the iTunes playing status from your Discord client, I would have to close the window. This one is _technically_ possible, but it would involve minimizing the app to the tray when you stop playing music, and then reopening the app when you start playing again.

If you have any further suggestions, do not hesitate to post them as issues here, or to send them to me via Discord (nint8835#4596)

**Comment by yashendra2797** [comment]
Aight mate. Thanks for the detailed explanation. Really appreciate the work you've put into this. Thanks!

**Comment by nint8835** [comment]
@yashendra2797 Your first feature suggestion actually turned out to be possible and has now been implemented

**Comment by yashendra2797** [comment]
Yeah I've been looking at the pull requests. Really fuckin dope work by all the contributors as well!
