### ISSUE TITLE
App just refuses to open

### ISSUE THREAD

**Issue by LilLegendGamerez** [nint8835/iTunesRichPresence#107]
When i try to open this app it refuses to open, I'm on Windows 11.

**Comment by helloitshecker** [comment]
Same Here! This is my windows 11 info.

![image](https://github.com/nint8835/iTunesRichPresence/assets/70046342/930c3da3-e575-4bc7-96c4-5f25415e534d)

**Comment by helloitshecker** [comment]
Also Debug Info of this app with gdb

![image](https://github.com/nint8835/iTunesRichPresence/assets/70046342/e5cfdc61-21cb-462d-86e8-98dabc53184b)

**Comment by xplt** [comment]
Try to check if your `user.config` configuration file is correct. It is located around:
`C:\Users\%YOUR_USER_NAME%\AppData\Local\iTunesRichPresence_Rewrit\iTunesRichPresence-Rewrit_Url_koerkjn2umsmbtmlnsie2yfg14mzcaei\2.5.0.0`
 In my case it was corrupted: half of it was filled with NULs (so, I guess, XML parser didn't like it):
![2023-12-24 (3)](https://github.com/nint8835/iTunesRichPresence/assets/6225402/438553f1-dd68-4c11-88a6-c4b58799e71a)
If it is corrupted, replace it ~~either from the `iTunesRichPresence-Rewrite.exe.config` file in the directory, where you placed iTunesRichPresence or replace it~~ with my config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <iTunesRichPresence_Rewrite.Properties.Settings>
            <setting name="RunOnStartup" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="PlayingTopLine" serializeAs="String">
                <value>%artist - %track</value>
            </setting>
            <setting name="PlayingBottomLine" serializeAs="String">
                <value>%playlist_type: %playlist_name</value>
            </setting>
            <setting name="PausedTopLine" serializeAs="String">
                <value>%artist - %track</value>
            </setting>
            <setting name="PausedBottomLine" serializeAs="String">
                <value>Paused</value>
            </setting>
            <setting name="DisplayPlaybackDuration" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Accent" serializeAs="String">
                <value>Orange</value>
            </setting>
            <setting name="ExperimentsEnabled" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="AppName" serializeAs="String">
                <value>iTunes</value>
            </setting>
            <setting name="ClearOnPause" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="MinimizeOnStartup" serializeAs="String">
                <value>False</value>
            </setting>
        </iTunesRichPresence_Rewrite.Properties.Settings>
    </userSettings>
</configuration>
```
**Edit**: looks like,  the app doesn't like parts "configSections" and "startup" from the config in the installation folder and expects only "userSettings" in the system config

**Comment by LilLegendGamerez** [comment]
Yeah lol eventually it worked.

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
