### ISSUE TITLE
Album cover (yes I understand this has been asked about before)

### ISSUE THREAD

**Issue by SkyeSpiderWitch** [nint8835/iTunesRichPresence#108]
So, I love this tool, it's an excellent piece of software, but I also agree with everyone asking for album art. I think it's important, but more than that I feel like there's GOT to be a way to get it working. Here's what I've got.
First, you mentioned a major issue was  "rich presence is restricted to 100 images that are uploaded through the website". I did some quick googling and found this https://s0hv.github.io/foo_discord_rich/docs/album-artwork/, which is a guide to a plugin for Foobar that gets automatic album covers working on discord. This video https://www.youtube.com/watch?v=E-uq0WT2pwk&ab_channel=aetry also goes over the process. It isn't the cleanest solution and might require some work on the user's end, but i think it could possibly help. Ofc tho, iTunes isn't Foobar, so I dug around some forums and found this one from like a decade ago https://www.vbforums.com/showthread.php?613104-RESOLVED-iTunes-Album-Artwork-Display. They ended up finding a way to get the art from iTunes, and from there it doesn't look like it would be _insanely_ difficult to get the artwork to discord to be displayed? Idk, but I figured this was at least worth bringing to your attention in case you (or someone else) wanted to actually try and get it working, bc this is at least a good starting place. 

PS: Here's the 2010 forum's working files in case ppl want them!
[itunes gui.zip](https://github.com/nint8835/iTunesRichPresence/files/13261127/itunes.gui.zip)
[itunes source.zip](https://github.com/nint8835/iTunesRichPresence/files/13261128/itunes.source.zip)

**Comment by nint8835** [comment]
Yeah the stuff now exists on Discord's end to do this, the limiting factor is actually implementing it in the app - I haven't actively worked on the app in years and I haven't been an iTunes user for even longer.

There's an existing issue open for this functionality (#95), going to close this issue as a duplicate. Thanks for the research / links though, might be helpful if this feature ends up being implemented.
