### ISSUE TITLE
Pausing a song makes title of the song disappear 

### ISSUE THREAD

**Issue by JeremyTM96** [nint8835/iTunesRichPresence#12]
Hello,

In these images I'm listening to a artist called Ja Mezz.
As you can see I have put artist first and second the song title.
And the time under it of course.

But the problem is when i pause the song the ''paused'' replaces the song title instead of just the time under it.

Not sure if it's a bug or not but it just looks weird if a artist is paused haha ;)

Thanks in advance.

Jeremy

![eeefefef](https://user-images.githubusercontent.com/38230789/38562807-b40571fa-3cdb-11e8-886c-b1efe5dbb1b7.PNG)
![wdadawdawdawdawd](https://user-images.githubusercontent.com/38230789/38562808-b41e7fa6-3cdb-11e8-8bf0-4f14678247de.PNG)

**Comment by nint8835** [comment]
In rich presence, there are two text areas: details (the top line, where your artist is at the moment), and state (the bottom line, where your track is at the moment). The way the software is currently set up is that when the player is paused, it overwrites the state with "Paused", causing what you posted. I should be able to add an option to make this optional.

**Comment by JeremyTM96** [comment]
ahhh I understand, Hope it can be added in the future. If not then it's okay haha.

Thanks

**Comment by nint8835** [comment]
Alright, a separate set of format settings for when the music is paused have been added and will be available in the next version.
