### ISSUE TITLE
Avast supposedly automatically removing software

### ISSUE THREAD

**Issue by nint8835** [nint8835/iTunesRichPresence#16]
A user has reported that their Avast is automatically deleting iTunesRichPresence.exe and flagging it as IDP.Generic.

Steps to be taken:
- [ ] Scan release version of software with Avast, ensure this issue is reproducible
- [ ] Submit executable as false positive to Avast
- [ ] Add warning message to readme, notifying users that Avast may delete the software

**Comment by crimist** [comment]
v2.2.0 [seems to be fine](https://www.virustotal.com/#/file/666fc902f7430edc6a377a387f7dfa799bbc5b072e3bb0514f9716a8dfaf4cb2/detection)

**Comment by yashendra2797** [comment]
Any progress on this? If everything is fine this should be closed, right?

**Comment by nint8835** [comment]
I haven't really looked into it yet, but I've stopped having people complain to me about it so I'll go ahead and close it.
