### ISSUE TITLE
Add theme selector UI

### ISSUE THREAD

**Issue by nint8835** [nint8835/iTunesRichPresence#17]
Currently the app uses a hardcoded theme (in rewrite) of light theme with orange accents. Add a theme selector UI to allow the user to change the theme and accent colours.

**Comment by yashendra2797** [comment]
Is it possible, on W10, to use theme colors? ie, those used by the system?

**Comment by nint8835** [comment]
It might be. I'm not quite sure, but the UI framework I'm using does support custom themes.

**Comment by nint8835** [comment]
Implemented with commit 363179a

**Comment by yashendra2797** [comment]
Much obliged!
