### ISSUE TITLE
Coverart?

### ISSUE THREAD

**Issue by abhiiously** [nint8835/iTunesRichPresence#18]
Is there plans to have cover art display? That would be amazing :D

**Comment by nint8835** [comment]
If discord ever adds support for it, it will be added as soon as I can possibly do it. However, at the moment rich presence is restricted to 100 images that are uploaded through the website, so you can't just say "use the image for the song I'm listening to"

**Comment by ReubenBTalbott** [comment]
Thanks for the reply.
