### ISSUE TITLE
Do I need to run this app every time I listened to music?

### ISSUE THREAD

**Issue by skeith** [nint8835/iTunesRichPresence#20]
Do I need to run this app every time I listened to music? or is it only needed to be run once?
Also, do I need Administrator privilege?

**Comment by nint8835** [comment]
iTunesRichPresence is designed to run in the background when you listen to music in iTunes. The software *generally* doesn't require admin, but sometimes permissions errors occur while trying to communicate with iTunes, and in these situations it is required.

**Comment by skeith** [comment]
I apologize if I misunderstood your answer, but you didn't seems answer my first half of the question. 

> Do I need to run this app every time I listened to music? or is it only needed to be run once?

However according to your answer, I assume I need to run it once on every startup boot, since I don't seem any details about it being able to hook itself into startup items/services

**Comment by nint8835** [comment]
The software does need to be started on every system boot, but there is an option in the settings menu to make it automatically start.
