### ISSUE TITLE
If display playback duration is disabled allow us to use a third textbox

### ISSUE THREAD

**Issue by pfych** [nint8835/iTunesRichPresence#27]
When Display playback duration isn't ticked there is an empty section that could be used for displaying more information.

For example right now I used
1. %track
2. %artist

but if we had a third box I could
1. %track
2. %album
3. %artist

It would be a really handy feature

**Comment by nint8835** [comment]
While a cool idea, that is unfortunately not how discord works. The playback duration isn't displayed using text we provide, but rather by giving a start and an end time, which discord uses on their side to generate the text. The only place we can actually provide our own text is in those two lines.
