### ISSUE TITLE
Name "Playing iTunes" to "Apple Music"

### ISSUE THREAD

**Issue by sacqsy** [nint8835/iTunesRichPresence#29]
Hi!

Personally I would like to see Apple Music in the place of iTunes in "Playing", is where I listen to my music.
Can you change this according to the user or predefine this or do you think it would be a good idea?

Awesome work! Thanks for everything :D

**Comment by nint8835** [comment]
That idea actually hasn't occurred to me before. It should be pretty simple to implement, but my computer isn't set up to work on iTunesRichPresence right now so I can't work on it at the moment.

**Comment by TellMeSac** [comment]
Oh. It would be incredible to be able to see it implemented at some point.
Thanks for the time to respond. ^^

**Comment by TellMeSac** [comment]
Oh. It would be incredible to be able to see it implemented at some point.
Thanks for the time to respond. ^^

**Comment by sacqsy** [comment]
Oh. It would be incredible to be able to see it implemented at some point.
Thanks for the time to respond. ^^

**Comment by nint8835** [comment]
Implemented in a49c191. Going live in v2.3.0
