### ISSUE TITLE
Start the program in the background, with Windows.

### ISSUE THREAD

**Issue by sacqsy** [nint8835/iTunesRichPresence#30]
Hi! Me again. Whew.

Currently, the program runs when Windows starts. It would seem excellent to me that it could start in the background, minimized. Do you think this could be possible or is it a good idea?

Thank you for the quick implementation of my Apple Music proposal, it was amazing!
Thanks, great job! Greetings.

**Comment by GijsDeBeun** [comment]
You can actually fix this yourself. Add the program shortcut to your startup folder and open the shortcut settings. There is a option to start it minimized [https://imgur.com/a/ZpwAZml](https://imgur.com/a/ZpwAZml).
Sorry for it being in dutch

**Comment by thatrobotdev** [comment]
I would also like this very much to be a setting!

**Comment by nint8835** [comment]
Implemented as the default behavior in v2.4.0.0
