### ISSUE TITLE
I want TOKEN TOOLBOX to add cumulative number of playback.

### ISSUE THREAD

**Issue by book000** [nint8835/iTunesRichPresence#35]
By having Discord display the cumulative number of playback, I think that opportunities to talk about songs with other users will increase. Please add it!

**Comment by nint8835** [comment]
It's incredibly difficult for the software to actually determine how many times you've listened to a song, and as a result the number would almost always be inaccurate.

**Comment by nint8835** [comment]
Turns out I was wrong, and iTunes *does* indeed provide a way to get total plays of a song.
