### ISSUE TITLE
Stop displaying status while paused

### ISSUE THREAD

**Issue by TheSiegeOfTampa** [nint8835/iTunesRichPresence#38]
Since your app overrides game presence I would like toggle in settings that would allow you to not update presence when music is paused.
for example. I start playing a game. I pause my music. Discord will be able to display game. While being able to keep the app running.

**Comment by nint8835** [comment]
Alright, your suggestion has been implemented in the form of the "Clear status when paused" checkbox in the settings menu of the newest version of the software.

**Comment by TheSiegeOfTampa** [comment]
Thank you kindly
