### ISSUE TITLE
Latest Update once minimized, can't open it back up

### ISSUE THREAD

**Issue by TheNightRider12** [nint8835/iTunesRichPresence#39]
On the latest update in the Releases tab.

Once app is opened and I go to minimize the app, the app minimizes but I am unable to double click on the minimized icon to open the program back up in order to exit the program or to change the settings around. 

If I want to close the app I have to go into Task Manager and end the process.

**Comment by TheSiegeOfTampa** [comment]
I experienced this as well but haven't tried agian since last night.

**Comment by nint8835** [comment]
Just took a look at the code and I'm guessing this is because the fix for #36 involved hiding the window, but the code that un-minimizes it doesn't show the window again. I'll try to have a bug fix out before next week.

**Comment by nint8835** [comment]
Alright, fix is now out in v2.4.1

**Comment by TheSiegeOfTampa** [comment]
It minimizes to the tray but when clicked it doesn't actually open the window. It just gives you a clickable item on the task bar again. So... Fixed sort of... Maybe...
