### ISSUE TITLE
It was determined to be a virus

### ISSUE THREAD

**Issue by yuchan2215** [nint8835/iTunesRichPresence#55]
avast detected idp.alexa.51 and isolated this software. (Only once)

**Comment by RuinTD** [comment]
> determined to be a virus

That's quite strong wording from someone claiming their antivirus only detected it once. I also looked up that virus and most links I found were relating to false positives. If you're doubtful, here's a link that shows scans from several different antiviruses:

https://www.virustotal.com/gui/url/43c3f3ac0e7f42c85fc58df54516640c7bf522de39b34efb57d24d38dc989522/summary

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
