### ISSUE TITLE
Status Refresh time

### ISSUE THREAD

**Issue by youssefA9** [nint8835/iTunesRichPresence#57]
The application take approximately 11 sec to respond to any change happened in the itunes like pause or skiping the song , i hope you take in the consideration the immediate refresh of any change happing.

**Comment by bwthur** [comment]
Discord Rich Presence has a rate limit of one update per 15 seconds.

**Comment by youssefA9** [comment]
couldn't it be much faster as i saw another rich presence refreshes immediately

**Comment by youssefA9** [comment]
couldn't it varies as some RP refresh instantly?

**Comment by nint8835** [comment]
Discord's new rich presence SDK has a more generous limit on the frequency of updates, but I'm unsure as to if I'm able to use that. I can definitely take a look into seeing how feasible it would be

**Comment by JustSpace2004** [comment]
I was just wondering if there was any way of getting rid of the application because everytime I try deleting it, it won't let me because it says its using another application

**Comment by JustSpace2004** [comment]
Just wondering because normally you should be able to just get rid of something but for whatever reason it won't delete the application

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
