### ISSUE TITLE
"xx:xx Left" continues to tick down despite music is paused.

### ISSUE THREAD

**Issue by nolsen42** [nint8835/iTunesRichPresence#6]
I been using iTunesRichPresence for a while, and I notice that the countdown till the music ends still keeps ticking, even if I pause the music.

And I also notice when it's playing, if you seek or rewind, the countdown doesn't update.

**Comment by nint8835** [comment]
The first thing should be fairly easy to fix, not sure about the second one

**Comment by nint8835** [comment]
Actually, thinking about it, both should be fairly easy to fix

**Comment by nint8835** [comment]
Fix to the second of those issues is to also add time checking to the polltimer, in addition to artist, track, and state. The first should be to see if the music is no longer playing, and to clear the countdown if that is the case
