### ISSUE TITLE
What can i do with experiments setting and how can i add genre token

### ISSUE THREAD

**Issue by thweenty7** [nint8835/iTunesRichPresence#67]
What can i do with experiments setting and how can i add genre token . tysm

**Comment by nint8835** [comment]
The experiments setting is a setting to enable functionality that was still a WIP, but the code existed for in the app. At the moment, there are no actual real features that it enables (and it will almost certainly be staying that way until it is removed). As for adding the genre token, someone just added a year token, so you can very easily use their code (PR #66) and the [docs for iTunes' API](http://www.joshkunz.com/iTunesControl/interfaceIITTrack.html) as a reference
