### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by afronob** [nint8835/iTunesRichPresence#68]
Hi there,

Thanks for this tool, but what about a Mac version ? 
Do you think that it's possible to do ?

Thank's again.

**Comment by nint8835** [comment]
As noted on the readme, there are currently no plans for a mac version of the software. However, the app is currently in the process of being rewritten, and after the rewrite is complete a mac version would in theory be possible. I will leave this issue open as the central issue for mac support.

**Comment by Fall1ngSky** [comment]
Hey! I just wanted to know if a macOS version of iTunesRichPresence would still be a possibility.

**Comment by nint8835** [comment]
Still a possibility, however no plans for it at the moment

**Comment by testerfruit** [comment]
weird, what kind of people wouldn't make their app native support on macOS ?
bunch of weird nerd

**Comment by Alonso245** [comment]
Hello, there is still a possibility to bring support to macOS?

**Comment by nint8835** [comment]
As mentioned previously, still a possibility, however no plans for it at the moment

**Comment by johnzoki** [comment]
I guess there's still no progress or interest in a Mac version?

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
