### ISSUE TITLE
Make it say "Listening to...) 

### ISSUE THREAD

**Issue by LynxReborn** [nint8835/iTunesRichPresence#70]
Currently the presence says "Playing Apple Music" but in my opinion it would be nicer if it would say "Listening to Apple Music". 

I am not that proficient in C# but I think the changes needed are easy. 
Here is a `public int type;` needed: 
https://github.com/nint8835/iTunesRichPresence/blob/f5be0b4f7ca7e5bf1fbf5c7bc069d4ef8b2cece8/DiscordRpc.cs#L39-L42 
Here too:  https://github.com/nint8835/iTunesRichPresence/blob/f5be0b4f7ca7e5bf1fbf5c7bc069d4ef8b2cece8/DiscordRpc.cs#L102-L108 
Here is a `_presence.type = type;` needed: 
https://github.com/nint8835/iTunesRichPresence/blob/f5be0b4f7ca7e5bf1fbf5c7bc069d4ef8b2cece8/DiscordRpc.cs#L127-L135 

Here is a `presence.type = 2;` needed between the two lines: 
https://github.com/nint8835/iTunesRichPresence/blob/f5be0b4f7ca7e5bf1fbf5c7bc069d4ef8b2cece8/DiscordBridge.cs#L131-L132 

But since I am not 100% sure if that is all maybe you should take a look over it first.

**Comment by nint8835** [comment]
That field exists, however Discord ignores anything that's not type "playing". See the following quote from the docs:
> ActivityType is strictly for the purpose of handling events that you receive from Discord; though the SDK/our API will not reject a payload with an ActivityType sent, it will be discarded and ***will not change anything in the client***.

Therefore, this is unfortunately not possible at this time.
