### ISSUE TITLE
Doesn't work on macOS Big Sur beta 4

### ISSUE THREAD

**Issue by minecrafthello** [nint8835/iTunesRichPresence#71]
It doesn't seem to connect with iTunes, as it says that there is no song playing when there is.

**Comment by nint8835** [comment]
This app does not support macOS. If you're using an app like this on iTunes you're either:
a) Running the app under some sort of compatibility layer, in which case this app won't work
b) You're using a different app

**Comment by minecrafthello** [comment]
I apologize for the confusion on my end, please discard my issue. Thank you for the quick response!
