### ISSUE TITLE
exe not opening

### ISSUE THREAD

**Issue by ShadowFlame740** [nint8835/iTunesRichPresence#75]
Pretty simple, trying to open the exe and nothing happens, nothing on the tray, nothing in task manager. Tried running as administrator, nothing happened, uninstalled and redownloaded, still nothing. It worked fine like 2 months ago but it just wont open anymore. No clue if this is an issue on my end or on the development end but any help is appreciated.

**Comment by samkawaii** [comment]
same here

**Comment by aniketpathak028** [comment]
same here as well

**Comment by aniketpathak028** [comment]
I found a solution that might help!
if you are on windows, then try this just download the .exe file and it will work!
https://github.com/kkevinm/iTunes-Discord-RP/releases/tag/1.5.7

**Comment by nint8835** [comment]
> I found a solution that might help!
> if you are on windows, then try this just download the .exe file and it will work!
> https://github.com/kkevinm/iTunes-Discord-RP/releases/tag/1.5.7

Please note, that while this may help, this is a separate piece of software from a different developer, so I can't offer any support for it.

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
