### ISSUE TITLE
Not working on Win10 v20H2 with iTunes 12

### ISSUE THREAD

**Issue by HeisenPat** [nint8835/iTunesRichPresence#76]
Hi,

is this application still working?
Didn't get the itunes status to show up in discord.

Windows 10 20H2
iTunes 12.10.10.2
Discord Stable 71615 (583a822)

**Comment by RushHour2k5** [comment]
Same issue. Attempted to use for the first time tonight, can see the EXE running in Task Manager, opens iTunes, drops memory, suspends, and closes. iTunes remains open and prompts about scripting when closing.

**Comment by BearTS** [comment]
Strange because it works for me

**Comment by haunt13** [comment]
Did you make sure to add the "game" itunes rich presence to your game activity on discord?

**Comment by snarkDADMin** [comment]
Working correctly here on Windows 10 21H2 LTSC, iTunes 12.12.7.1 and Discord stable 165943 (15bdaf0)

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
