### ISSUE TITLE
Change icon to new Apple Music logo

### ISSUE THREAD

**Issue by codenm** [nint8835/iTunesRichPresence#79]
The Apple Music icon currently being used is now outdated.

**Comment by ClassifiedDuck** [comment]
@nint8835 Here is the new logo in the ico format. Hope that helps. :)
[DiscordItunes.ico.zip](https://github.com/nint8835/iTunesRichPresence/files/6070123/DiscordItunes.ico.zip)

**Comment by nint8835** [comment]
Apple Music app has now been updated to use the latest Apple Music logo from Apple's brand guidelines, but iTunes has been left using the existing iTunes logo. If you want the latest logo, ensure you have your app name set to apple music in settings. If you wish to have the latest logo with the itunes app, a separate issue has been opened for that (https://github.com/nint8835/iTunesRichPresence/issues/88)
