### ISSUE TITLE
iTunesRichPresence for MAC!?!?!

### ISSUE THREAD

**Issue by ClassifiedDuck** [nint8835/iTunesRichPresence#81]
Hello! I was wondering if you could make a version for Mac?!?!

**Comment by nint8835** [comment]
Duplicate of #68, #37, #23

As noted in the readme, there are currently no plans for a macOS version of the app. There is an existing issue (#68) open tracking this feature request.

**Comment by ClassifiedDuck** [comment]
Okay, thank you! I gave you the new logo here,
https://github.com/nint8835/iTunesRichPresence/issues/79
