### ISSUE TITLE
Change Rich Presence Icon to 2021 Apple Music Icon

### ISSUE THREAD

**Issue by PixelCrafterOS** [nint8835/iTunesRichPresence#84]
Hi, I know this is similar to [this issue](https://github.com/nint8835/iTunesRichPresence/issues/79), but not the same.

The icon in the rich presence (the one provided by the discord application image) is still the old iTunes icon, and I would appreciate it being updated to macOS 11's Apple Music icon or iOS 14's Apple Music icon. From my knowledge, this can't be changed by the user, and has to be changed on the discord developer page.

Thanks!

**Comment by mannotcool** [comment]
Apple still hasn't updated the icon for iTunes on windows.

**Comment by PixelCrafterOS** [comment]
I know, but the iTunes logo is old and outdated, and there should at least be the option to change it to the newer Apple Music icon.

**Comment by LeviSnoot** [comment]
I'm super glad someone else had already created an issue for this, and I agree fully. I want the Apple Music icon despite iTunes still being around on Windows.

**Comment by mannotcool** [comment]
Someone should make a fork fixing it. Or even make a pull request.

**Comment by nint8835** [comment]
Just updated the Apple Music app to use the latest logo from Apple's brand standards, so if you wish to use the updated logo change your app name in settings to Apple Music. I will open a separate issue to allow selection of the icon for the iTunes app.

**Comment by nint8835** [comment]
Icon selection issue: https://github.com/nint8835/iTunesRichPresence/issues/88
