### ISSUE TITLE
Add different styling for Podcasts

### ISSUE THREAD

**Issue by ghost** [nint8835/iTunesRichPresence#89]
This Playing Status suits better for Podcasts:

![image](https://user-images.githubusercontent.com/71291013/130199958-eb0ead69-fb81-469f-ad25-fde4e85324ba.png)

**Comment by nint8835** [comment]
Just to confirm, is the intended result here to allow selecting different settings per media type?

**Comment by ghost** [comment]
I was thinking that it could also be a good idea. But I am podcast guy, so I tried to give my version only

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
