### ISSUE TITLE
Option to display "Listening To" instead of "Playing"

### ISSUE THREAD

**Issue by dotalw** [nint8835/iTunesRichPresence#9]
So discord has this `Listening To` game statue, my suggestion is to add an option to the tray icon to change the game statue from `Playing iTunes` to something like `Listening To iTunes` or `Listening To SONG_NAME` (or it comes by default like that), it looks better in my opinion, and has a better description of what i'm actually doing.

Although, i'm not sure if Discord's rich presence allow such thing, but it should be allowed i guess, since they have their own Spotify rpc where it's using `Listening To`

**Comment by nint8835** [comment]
While that would be nice to do, it is unfortunately not possible. While the "Listening to" game state does exist, rich presence applications are unable to control what game state they use, meaning we are required to use "Playing" instead. If Discord is ever updated to make it possible, however, I will make the change.

**Comment by dotalw** [comment]
Understandable, well i guess we'll have to wait until they make it possible.
