### ISSUE TITLE
Does not work when running as an administrator

### ISSUE THREAD

**Issue by inyongthegr8** [nint8835/iTunesRichPresence#92]
My discord is running as an administrator by default because there are some games that cannot be hooked when games are running as an administrator (specifically streaming the likes of Genshin Impact, etc).

Trying to run this app as an administrator does not actually open.

Steps to reproduce:

1. Run iTunesRichPresence-Rewrite.exe as Administrator.
2. Nothing happens.

OS used: Windows 11 (10.0.22000.493)

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
