### ISSUE TITLE
Add option for album cover as status icon

### ISSUE THREAD

**Issue by Storby42** [nint8835/iTunesRichPresence#95]
I think it would be kinda nice if the app had an option to set the current album cover art as the icon for the status instead of the apple music logo. Not sure how feasible this is, but I would love this feature! thanks! (imagine an enhancement tag here)

**Comment by jackharrhy** [comment]
no

**Comment by nint8835** [comment]
I would have previously tagged this as a duplicate (since this has been suggested many times), but the functionality to do this now exists, so going to leave this issue open as the main issue for tracking that feature request

**Comment by ghost** [comment]
+1 to this feature. This would make the app so much better.

> The functionality to do this now exist

How do you enable it?

**Comment by jackharrhy** [comment]
> +1 to this feature. This would make the app so much better.
> 
> > The functionality to do this now exist
> 
> How do you enable it?

I believe @nint8835 is referring to the possibility within the Discord API for presence applications to use arbitrary image URLs, but this would still have to be built out within this repository.

**Comment by Ammar360** [comment]
I believe there is a way to do this! I've found a few other projects on Github like https://github.com/wxllow/applemusicrp that have figured out a way to do it, and this would really make this project perfect!

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
