### ISSUE TITLE
Change App Name

### ISSUE THREAD

**Issue by DarkStiller** [nint8835/iTunesRichPresence#96]
Is there the possebility to add a neutral app name link "Music" or to give the user the option to choose a costum one?

**Comment by ChokunPlayZ** [comment]
it's impossible without changing the app id itself, right now the original author did not allow it so you will have to recompile the program

**Comment by DarkStiller** [comment]
> it's impossible without changing the app id itself, right now the original author did not allow it so you will have to recompile the program

Thanks captain obvious. I found the point, where the it is written in the code. But I am not able to compil it with the plugin and so on.

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
