### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by devonaw** [nint8835/iTunesRichPresence#97]
I know, not really a helpful issue title, but I have no idea why it's not working. I started using iTunesRichPresense a few months ago but then it just randomly stopped working. Now I'm finally reporting my problem. I have discord open, I have iTunes playing a song, I have activity status on on discord.
I'm happy to troubleshoot to find what's causing the problem.

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
